build:
  docker:
    web: Dockerfile
  config:
    RAILS_ENV: development
    # FOO: bar
# release:
#   command:
#     - ./deployment-tasks.sh
#   image: worker
run:
  web: bin/rails server -p ${PORT:-5000} -e $RAILS_ENV
  # worker: python myworker.py
  # asset-syncer:
  #   command:
  #     - python asset-syncer.py
  #   image: worker